# Copyright (C) 2017-2018 Project-ODE
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Hyperswitch configuration for ODE-FeatureService api:annotation-set endpoints
# Author: Erwan Keribin


swagger: '2.0'
info:
  version: '1.0.0-beta'
  title: ODE FeatureService Annotation Task API
  description: ODE FeatureService Annotation Task API
  termsofservice: TBD
  contact:
    name: ODE-Project Team
    email: TBD
    url: TBD
  license:
    name: GNU General Public Licence, v3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
paths:
  /campaign/{id}/my-list:
    get:
      tags:
        - ODE FeatureService annotation task listing function
      summary: Lists annotation tasks for a given campaign-id and currently logged-in user
      description: |
        Returns a list of the currently logged-in user annotation tasks for the identified campaign
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: Annotation Campaign ID
          type: string
          required: true
      responses:
        '200':
          description: list of user campaign annotation tasks
          schema:
            $ref: '#/definitions/annotation-task-list'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - verify_token:
            request:
              method: 'get'
              uri: /{domain}/sys/authentication/verify-token
              headers: '{{request.headers}}'
            return_if:
              status: ['4xx', '5xx']
        - get_from_backend:
            request:
              uri: /{domain}/sys/annotation-task/campaign/{id}/my-list
              current_user: '{{verify_token.body.token.aud}}'
      x-monitor: false

definitions:
  # A https://tools.ietf.org/html/draft-nottingham-http-problem
  problem:
    required:
      - type
    properties:
      type:
        type: string
      title:
        type: string
      detail:
        type: string
      instance:
        type: string

  annotation-task-list:
    type: array
    items:
      properties:
        id:
          type: integer
        status:
          type: integer
        filename:
          type: string
        dataset_name:
          type: string
        start:
          type: string
        end:
          type: string
